### ISSUE TITLE
It cannot play several times on macOS

### ISSUE THREAD

**Issue by daijuk** [hajimehoshi/oto#136]
I tried Oto on macOS with example source code.
It works well if trying is just once.

However playing sound several times is not working well.

Like this.
```
func main() {
	flag.Parse()
	if err := run(); err != nil {
		panic(err)
	}
	if err := run(); err != nil {
		panic(err)
	}
}
```

The thread/goroutine looks blocked.
I tried it also on Windows and Linux. It works well.

Could you check it? Thank you.

**Comment by hajimehoshi** [comment]
What does run do? Does run create the context?

**Comment by daijuk** [comment]
Thank you for reply.
It means reproducible step?

1. Modify main.go at example directory.
   Duplicate related calling run function.
   Like this.
```
    ...[ommited]
	wg.Wait()
	c.Close()
	return nil
}

func main() {
	flag.Parse()
	if err := run(); err != nil {
		panic(err)
	}
	if err := run(); err != nil {
		panic(err)
	}
}
```

2. Run the example program
```
$ go run main.go
```

3. It will not play the second one on macOS.

I tried it on macOS Big Sur. Also I tried it on macOS Mojave before. There was same problem.

Thank you.

**Comment by hajimehoshi** [comment]
Ah, `run` is the function in the example. OK I got it.

I'll take a look this later.

**Comment by yuikns** [comment]
I can reproduce the issue

```
$ uname -a
Darwin algac 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
$ cc --version
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

In the first time we create the NewContext, function `oto_render` in `driver_darwin.go` will called periodically. However it will never called in the next round.

According to some survey, the root cause is when we call `Close`, sometimes the `oto_render` has not return yet, and after its timeout, the oto_render will blocked and which will also block the RunLoop.

Please see the #145 for my fix. Hoping it helps.

**Comment by bloeys** [comment]
Hey everyone, seems this bug is back on MacOS Monterey with M1 chip (not sure about intel mac with Monterey).
This can be reproduced in the same way the original issue did, use the oto example code and run it twice:
```go
func main() {
	flag.Parse()
	if err := run(); err != nil {
		panic(err)
	}

	if err := run(); err != nil {
		panic(err)
	}
}
```

It also happens if I create two different contexts with one player each and play one at a time. Only the first player/context works and the second hangs with non-zero `UnplayedBufferSize`.

If you want to move this to its own issue and reference this one I can do that :)

**Comment by hajimehoshi** [comment]
Currently only one context can be created, so this is a known issue. I don't plan to make it possible to make multiple contexts so far.

**Comment by bloeys** [comment]
Oh thanks for the info, didn't know that. So I think doing `run` twice in the example creates two contexts which breaks things. Sorry if I missed this, but is this mentioned anywhere?

Might make sense to write even a basic docs section in the readme with a small usage example and notes about things like this, fact that you have to type-assert to get access to some functions etc

Should make it more friendly to use. I wouldn't mind helping by writing a draft of a small docs section like that if you like.

**Comment by Asday** [comment]
I could have sworn there was mention of it [here](https://pkg.go.dev/github.com/hajimehoshi/oto/v2#Context) but apparently I'm wrong.  The closest mention is in `NewContext()`.

Perhaps elaborate in there, and also mention that only one can exist at a time under `Context{}`.

**Comment by hajimehoshi** [comment]
@bloeys Yeah, I understand the current documentations are not enough. I'd appreciate if you could help that... Thanks!

@Asday I agree the note also should be in Context{} in addition to NewContext
