### ISSUE TITLE
Process ends before the music finishes when `io.Copy` is used

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#36]
Reported by @pankona

**Comment by hajimehoshi** [comment]
This might NOT be a bug: `Write`'s responsibility is to write the given bytes to its buffer and it doesn't have to wait until the playing is finished. Rather, waiting until the buffer is consumed would cause glitches.

**Comment by shurcooL** [comment]
Agreed, `io.Copy` may finish sooner. It shouldn't block past that.

Here are some thoughts. I'm not an expert on audio, so it's possible there are caveats I haven't considered.

You need some mechanism of either being able to tell when the player has gotten to the end of buffered data, or to tell it to block until so.

A traditional solution, if you want to think about this as file descriptors, would be to add a [`Flush() error`](https://godoc.org/bufio#Writer.Flush) method to the writer. Then, callers can do:

```Go
err = io.Copy(w, r)
if err != nil {
	// Handle error.
}

// Wait for player to finish playing what's in its buffer.
err = w.Flush()
if err != nil {
	// Handle error.
}
```

You already have a `Close` method. I think it might be okay to keep that as is: to forcibly stop playing right away. Then it's possible to stop playing sounds without waiting, or to wait.

**Comment by hajimehoshi** [comment]
> You already have a Close method. I think it might be okay to keep that as is: to forcibly stop playing right away. Then it's possible to stop playing sounds without waiting, or to wait.

I have a different opinion. As `Write` already waits for the all given bytes written to the buffer, there should not be a significant change between `Close` waiting for the buffer consumed and not. So I think `Close` can block until the buffer is empty. And if I change `Close` to do so, the current example should be improved without its code change.

> Edit: Also, you might want to tie this into the underrun callback. Effectively, to wait until music is done playing, you're looking for the moment when underrun is just about to happen.

I forgot the existence of the underrun callback :-) To be honest, I don't use this API for my personal use.

**Comment by hajimehoshi** [comment]
To clarify the things:

1. `Write` is called
2. The given bytes to `Write` are written to its inner buffer
3. The inner buffer is played

2. and 3. occurs in almost same but different timings. This issue is about this time lag. As `io.Writer` requires, `Write` waits until the given bytes are written to the buffer. When the buffer is full, `Write` is blocked until the buffer is consumed (i.e. played).

**Comment by shurcooL** [comment]
That sounds like a reasonable first step to take. It's much simpler. If people really want a way to stop playing sound forcibly without waiting for buffer to be used up, a way of accomplishing that can be added in the future.

**Comment by hajimehoshi** [comment]
@pankona I'd be happy if you could confirm that Oto works as you expected :-)

**Comment by hajimehoshi** [comment]
gently ping @pankona

**Comment by pankona** [comment]
Ack. :eyes:
Sorry to be late. I'll confirm.

**Comment by vsivsi** [comment]
Sorry to comment on a closed issue, but I think I'm still seeing this with the current version.

The reproduction is actually the project example code: https://github.com/hajimehoshi/oto/blob/master/example/main.go

If I understand it correctly, that code plays 3 tones, each 3 seconds long, but staggering their starts by 1 second:

```
Expected:

Time     0--1--2--3--4--5          
Freq C   |########|
Freq E      |########|
Freq G         |########|

Actual:

Time     0--1--2--3--4--5          
Freq C   |########|
Freq E      |#####|
Freq G         |##|
```

Adding this `time.Sleep` produces the expected behavior:

```go
	wg.Wait()
	time.Sleep(3 * time.Second)  // Ensure no context close until playing is complete
	c.Close()
```

Forgive me if I'm misunderstanding, but isn't this what this issue was supposed to fix?

Without a `c.Flush()` or some other way to know when all of the players have actually stopped, how to prevent this kind of truncation short of the type of hack I introduced above?

**Comment by hajimehoshi** [comment]
Hi,

I could not reproduce your issue (on macOS). What environment are you using?

**Comment by vsivsi** [comment]
Hi, I'm also on MacOS, version 10.15.7 using go1.15.3 and v0.6.6 of oto.

I just ran it again to make sure it wasn't a fluke, and it truncates the playback every time the same.

**Comment by vsivsi** [comment]
Okay this is very interesting... I get different behavior depending on which sound output I choose on the Mac.

If I use the internal speaker (2019 Mac Pro), it works correctly.

But if I use an AirPlay device (which I usually do for streaming music from my Mac), then I get the issue above.

Feels like a timing bug, as there's going to be more latency sending out over the network to the speakers.

**Comment by hajimehoshi** [comment]
You guess makes sense. I've never used AirPlay, but I'd appreciate if you'd suggest how to fix this issue. Thanks!

**Comment by vsivsi** [comment]
I just did a few trials, and the latency to start a new Airplay stream (time from example program load until sound) is ~2.5 sec, in addition to network latency, an Airplay stream is both compressed and encrypted (and the reverse on the other end). So my 3 second sleep worked because it was longer than that. Some of that latency will depend on the network, but my guess is that most of it is buffering in various places.

You could add a 3-5 sec sleep inside of `Context.Close()` before closing the audio driver. That would probably catch most such cases, but it would mean that the `Close()` behavior would no longer act immediately when that is desired. My hack above wasn't so bad now that I know it's necessary, but you'd like to avoid seeing this issue crop up over and over.

**Comment by hajimehoshi** [comment]
Thanks! So probably I'll add a comment to `Close` about this heads up for environments requiring encoding/decoding delay. Extending the sleeping time makes UX a little worse for other environments, so I'd like to avoid it. Does this make sense?

**Comment by hajimehoshi** [comment]
In v2, `Close` no longer exists and the situation has changed.
